Repository Team-Micras/MicrasFirmware, pull requests merged in 2024-04, with the labels that each got.

#9 :sparkles: Adiciona suporte ao formatador clang-format
  .clang-format
  .editorconfig
  .githooks/pre-commit
  .vscode/extensions.json
  .vscode/settings.json
  CMakeLists.txt
  LICENSE
  cfg/target.cpp
  cfg/target.hpp
  cmake/targets.cmake
  cmake/templates/helpme.in
  inc/controller/micras_controller.hpp
  inc/hal/adc_dma.hpp
  inc/hal/crc.hpp
  inc/hal/encoder.hpp
  inc/hal/flash.hpp
  inc/hal/gpio.hpp
  inc/hal/mcu.hpp
  inc/hal/pwm.hpp
  inc/hal/pwm_dma.hpp
  inc/hal/spi.hpp
  inc/hal/timer.hpp
  inc/proxy/argb.hpp
  inc/proxy/battery.hpp
  inc/proxy/button.hpp
  inc/proxy/buzzer.hpp
  inc/proxy/current_sensors.hpp
  inc/proxy/dip_switch.hpp
  inc/proxy/distance_sensors.hpp
  inc/proxy/fan.hpp
  inc/proxy/imu.hpp
  inc/proxy/led.hpp
  inc/proxy/locomotion.hpp
  inc/proxy/rotary_sensor.hpp
  inc/proxy/rotary_sensor_reg.hpp
  inc/proxy/serializable_interface.hpp
  inc/proxy/storage.hpp
  inc/proxy/torque_sensors.hpp
  src/controller/micras_controller.cpp
  src/hal/crc.cpp
  src/hal/flash.cpp
  src/hal/gpio.cpp
  src/hal/timer.cpp
  src/proxy/argb.cpp
  src/proxy/button.cpp
  src/proxy/current_sensors.cpp
  src/proxy/dip_switch.cpp
  src/proxy/distance_sensors.cpp
  src/proxy/imu.cpp
  src/proxy/led.cpp
  src/proxy/locomotion.cpp
  src/proxy/rotary_sensor.cpp
  src/proxy/storage.cpp
  src/proxy/torque_sensors.cpp
  tests/bin/test_main.cpp
  tests/inc/test_core.hpp
  uncrustify.cfg
Labels: enhancement

#10 :sparkles: Adiciona documentação Doxygen
  .gitignore
  Doxyfile
  cmake/targets.cmake
  cmake/templates/helpme.in
Labels: documentation, enhancement

#12 Hotfix/storage start symbol
  inc/proxy/imu.hpp
  inc/proxy/storage.hpp
  src/proxy/storage.cpp
Labels: enhancement

#14 Feature/storage test
  CMakeLists.txt
  cmake/config_validation.cmake
  cmake/utilities.cmake
  config/target.hpp
  micras_proxy/include/micras/proxy/serializable_interface.hpp
  micras_proxy/include/micras/proxy/storage.hpp
  micras_proxy/src/storage.cpp
  tests/bin/proxy/test_storage.cpp
Labels: enhancement

#15 🐛 Fix buzzer wait function
  CMakeLists.txt
  config/target.hpp
  micras_hal/include/micras/hal/adc_dma.hpp
  micras_proxy/src/buzzer.cpp
Labels: bug
